"""
app/modules/audit/audit_repository.py
--------------------------------------
Data-access layer for audit log records.

All SQLAlchemy queries related to the ``audit_logs`` table live here.
"""

import logging
from typing import Optional

from sqlalchemy.orm import Session

from app.modules.audit.audit_model import AuditLog

logger = logging.getLogger(__name__)


class AuditRepository:
    """
    Encapsulates all database operations for :class:`AuditLog` entities.
    """

    def create(
        self,
        db: Session,
        user_id: str,
        action: str,
        entity_type: Optional[str] = None,
        patient_uhid: Optional[str] = None,
        ip_address: Optional[str] = None,
    ) -> AuditLog:
        """
        Persist a new audit log entry.

        :param db:           Active database session.
        :param user_id:      Actor's username or system identifier.
        :param action:       Action label (e.g. ``APPROVED_PATIENT``).
        :param entity_type:  Affected entity class name.
        :param patient_uhid: UHID of the affected patient.
        :param ip_address:   Originating IP address.
        :return: The persisted :class:`AuditLog` instance.
        """
        entry = AuditLog(
            user_id=user_id,
            action=action,
            entity_type=entity_type,
            patient_uhid=patient_uhid,
            ip_address=ip_address,
        )
        db.add(entry)
        db.commit()
        db.refresh(entry)
        logger.debug("Audit entry created: %s by %s", action, user_id)
        return entry

    def get_by_patient(self, db: Session, patient_uhid: str) -> list[AuditLog]:
        """
        Retrieve all audit logs related to a specific patient.

        :param db:           Active database session.
        :param patient_uhid: UHID to filter by.
        :return: List of :class:`AuditLog` records ordered by timestamp.
        """
        return (
            db.query(AuditLog)
            .filter(AuditLog.patient_uhid == patient_uhid)
            .order_by(AuditLog.timestamp.desc())
            .all()
        )

    def get_by_user(self, db: Session, user_id: str) -> list[AuditLog]:
        """
        Retrieve all audit logs generated by a specific user.

        :param db:      Active database session.
        :param user_id: Username to filter by.
        :return: List of :class:`AuditLog` records ordered by timestamp.
        """
        return (
            db.query(AuditLog)
            .filter(AuditLog.user_id == user_id)
            .order_by(AuditLog.timestamp.desc())
            .all()
        )


audit_repository = AuditRepository()
